CREATE TABLE IF NOT EXISTS officialstudents (
    id INT(8) NOT NULL PRIMARY KEY,
    password VARCHAR(30) NOT NULL,
    fullName VARCHAR(30) NOT NULL,
    sex VARCHAR(30) NOT NULL,
    birthdate VARCHAR(30) NOT NULL,
    course VARCHAR(30) NOT NULL,
    address VARCHAR(30) NOT NULL,
    email VARCHAR(55) NOT NULL,
    cNumber VARCHAR(20) NOT NULL,
    lrn BIGINT(20) NOT NULL,
    yearLevel INT(10) DEFAULT '1',
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);